### ISSUE TITLE
v0.1 Dgraph operator roadmap

### ISSUE THREAD

**Issue by fristonio** [dgraph-io/dgraph-operator-archive#2]
- [x] Multiple cluster management
- [x] Dgraph cluster scalein and scaleout
- [ ] Dgraph cluster upgrade using operator
- [ ] Helm chart support for operator
- [x] Automatic registration and validation of Dgraph CRDs
- [ ] Integrate testing for operator

**Comment by chrishiestand** [comment]
I have been considering writing a dgraph operator for our own use-case. One thing that is, in particular, important to us is bulk loading. My plan was to use a zero sidecar container along with alpha init containers (both containing code specific to our workflow) to facilitate the setup. I understand that bulk loading with custom containers is not on the v0.1 roadmap. Any idea if this will be possible in the future, or how bulk loading is going to be facilitated down the road(map)?

At this point, I'm thinking that if the operator supports a custom zero sidecar along with a custom alpha init container, it should work fine with custom bulk loading logic.

**Comment by fristonio** [comment]
Hey @chrishiestand, Thanks for your interest in Dgraph.
dgraph-operator is in very early stages of development. As of 0.1 I don't think we will be looking to incorporate this feature, but yeah this does seem like a reasonable feature to have and we will try to integrate this in a future release.
We might need to brainstorm more about the best approach to do this with the operator though.

It would be really great if you can create an issue describing this in a bit more detail. We will keep an eye on it in our future releases.

**Comment by chrishiestand** [comment]
@fristonio I've created such an issue: https://github.com/dgraph-io/dgraph-operator/issues/13

**Comment by fristonio** [comment]
@chrishiestand thanks a lot, really appreciate putting efforts in writing a detailed description of the issue.
